parameters:
- name: subscription
  displayName: Scopes
  type: string
  default: regression
  values:
  - smoke
  - regression

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main

trigger:
- main

pool:
   vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
    architecture: 'x64'

- script: |
- task: CmdLine@2
  inputs:
    script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: CmdLine@2
  inputs:
    ${{ if contains(parameters.subscription, 'smoke') }}:
      script: |
        pytest -m smoke
    ${{ if contains(parameters.subscription, 'regression') }}:
      script: |
        pytest
  displayName: 'pytest'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'result.xml'

- task: PublishHtmlReport@1
  displayName: 'Publish HTML Report'
  inputs:
    reportDir: 'pyreport.html'
    tabName: 'PytestPyreport'